### PR TITLE
added vnc config

### PR DESCRIPTION
**Pull request by behrica**
Taken from https://github.com/PEZ/pirate-lang

### CODE REVIEW

**Comment by PEZ** [comment]
Thanks! This is a really good idea. I am a bit worried that it creates a distraction. At least without some mention in the INSTRUCTIONS.md file.

I'm thinking we can ”solve” this in two ways:

1. Update the INSTRUCTIONS.md file so that the user knows what it is and to wait with playing. with it.
2. Change the `onOpen` for port 6080 to not open the preview automatically.

I am leaning towards option 2. Then we can have it as part of the `welcome_to_clojure.clj` guide to first open the preview and then play with some code to create an app. WDYT?

**Comment by behrica** [comment]
Yes, I had it first switched of.
but then I noticed that it is not super obvious, how to show it.
But yes, we can add it to docu.

Desktop apps are not the first use case for beginners, indeed.

I can do that.

**Comment by behrica** [comment]
Maybe the main "reason" for this change, is not really to allow "developing Desktop apps", but to avoid
that a standard clojure command fails in Calva:
(while it does work on a Desktop computer)

```clojure
( clojure.inspector/inspect)
```

So we can just mention somewhere that   "frames" will be open in the VNC and how to see those.

**Comment by PEZ** [comment]
Thanks! I'll figure a bit about where and how to show how to open the VNC in preview or in a new brower window.

**Pull request merged**
